// This file will be auto-generated by Supabase CLI
// For now, manually defining types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      families: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          name: string;
          neighborhood: string | null;
          location_lat: number;
          location_lng: number;
          location_city: string | null;
          location_zip: string | null;
          location_point: unknown; // PostGIS geography
          bio: string | null;
          photo_url: string | null;
          interests: string[];
          verified: boolean;
          phone_verified: boolean;
          privacy_radius: number;
          active: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["families"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["families"]["Insert"]>;
      };
      children: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          family_id: string;
          name: string;
          age_years: number;
          age_months: number | null;
          interests: string[];
          school_age_group: "infant" | "toddler" | "preschool" | "elementary" | "middle" | "high" | null;
        };
        Insert: Omit<Database["public"]["Tables"]["children"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["children"]["Insert"]>;
      };
      connections: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          requester_family_id: string;
          receiver_family_id: string;
          status: "pending" | "accepted" | "declined";
          message: string | null;
        };
        Insert: Omit<Database["public"]["Tables"]["connections"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["connections"]["Insert"]>;
      };
      conversations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          last_message_at: string;
          family_ids: string[];
        };
        Insert: Omit<Database["public"]["Tables"]["conversations"]["Row"], "id" | "created_at" | "updated_at" | "last_message_at">;
        Update: Partial<Database["public"]["Tables"]["conversations"]["Insert"]>;
      };
      messages: {
        Row: {
          id: string;
          created_at: string;
          conversation_id: string;
          sender_family_id: string;
          content: string;
          read: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["messages"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
      };
      events: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          host_family_id: string;
          title: string;
          description: string | null;
          location_name: string | null;
          location_address: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_point: unknown | null;
          datetime: string;
          age_range_min: number | null;
          age_range_max: number | null;
          max_families: number | null;
          attendees: string[];
          visibility: "connections_only" | "neighborhood" | "public";
          active: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["events"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>;
      };
      reports: {
        Row: {
          id: string;
          created_at: string;
          reporter_family_id: string;
          reported_family_id: string;
          reason: string;
          details: string | null;
          status: "pending" | "reviewed" | "resolved" | "dismissed";
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: Omit<Database["public"]["Tables"]["reports"]["Row"], "id" | "created_at" | "reviewed_at" | "reviewed_by">;
        Update: Partial<Database["public"]["Tables"]["reports"]["Insert"]>;
      };
      blocks: {
        Row: {
          id: string;
          created_at: string;
          blocker_family_id: string;
          blocked_family_id: string;
        };
        Insert: Omit<Database["public"]["Tables"]["blocks"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["blocks"]["Insert"]>;
      };
    };
    Functions: {
      get_nearby_families: {
        Args: {
          user_lat: number;
          user_lng: number;
          radius_meters?: number;
          limit_count?: number;
        };
        Returns: {
          id: string;
          name: string;
          neighborhood: string | null;
          bio: string | null;
          photo_url: string | null;
          interests: string[];
          verified: boolean;
          phone_verified: boolean;
          privacy_radius: number;
          blurred_lat: number;
          blurred_lng: number;
          location_city: string | null;
          location_zip: string | null;
          distance_meters: number;
          children_count: number;
          children_ages: string | null;
          shared_interests_count: number;
        }[];
      };
    };
  };
}

